global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'local-project'

scrape_configs:
  - job_name: 'local'
    static_configs:
#TODO: find same solution for linux systems
      - targets: ['host.docker.internal:7071']
##      - targets: ['docker.for.unix.localhost:7071']


