{
 "title": "Main",
 "tags": [
  "server",
  "jvm"
 ],
 "time": {
  "from": "now-5m",
  "now": false,
  "to": "now"
 },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "15s,30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Objects in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rtb_spaces_gameobjects_count", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Spaces count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rtb_spaces_count", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1s",
     "expr": "jvm_memory_bytes_used",
     "legendFormat": "Used {{area}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22jvm_memory_bytes_used%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-6-10%206%3A1%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "1s",
     "expr": "jvm_memory_bytes_max",
     "legendFormat": "Max {{area}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22jvm_memory_bytes_max%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-6-10%206%3A1%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1s",
     "expr": "jvm_memory_pool_bytes_used",
     "legendFormat": "{{pool}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22jvm_memory_pool_bytes_used%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22901s%22%2C%22end_input%22%3A%222015-6-10%206%3A0%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory pool committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "30s",
     "expr": "jvm_memory_pool_bytes_committed",
     "legendFormat": "{{pool}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22jvm_memory_pool_bytes_committed%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2218570s%22%2C%22end_input%22%3A%222015-6-10%200%3A14%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count[$interval])",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "1s",
     "expr": "irate(jvm_gc_collection_seconds_sum[$interval])",
     "legendFormat": "{{gc}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22increase(jvm_gc_collection_seconds_sum%7Binstance%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-6-10%206%3A7%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Process cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "rate(process_cpu_seconds_total[$interval])",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22increase(process_cpu_seconds_total%7Binstance%3D%5C%22%24host%5C%22%7D%5B%24interval%5D)%22%2C%22range_input%22%3A%2219996s%22%2C%22end_input%22%3A%222015-6-9%2014%3A30%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current" }
   ]
  }
 ]
}