version: '3.6'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.8.1
    ports:
      - "9090:9090"
    volumes:
      - /c/Users/Stepan/AppData/Roaming/test/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


#  grafana:
#    container_name: grafana
#    image: grafana/grafana:5.4.3
#    depends_on:
#      - prometheus
#    volumes:
#      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
#    ports:
#      - "3000:3000"

volumes:
  prometheus_data:
